I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 62, in script
    monika "[position]"
  File "game/dialogues/quests.rpy", line 44, in execute
    screen quest_description:
  File "game/dialogues/quests.rpy", line 44, in execute
    screen quest_description:
  File "game/dialogues/quests.rpy", line 49, in execute
    window:
  File "game/dialogues/quests.rpy", line 55, in execute
    text quest_description:
Exception: Cannot display None as text.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 62, in script
    monika "[position]"
  File "D:\downloads\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\exports.py", line 1493, in say
    who(what, *args, **kwargs)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\character.py", line 1394, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\character.py", line 1045, in do_display
    display_say(who,
  File "D:\downloads\renpy-8.2.1-sdk\renpy\character.py", line 741, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\downloads\renpy-8.2.1-sdk\renpy\display\core.py", line 2687, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\downloads\renpy-8.2.1-sdk\renpy\display\displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\display\displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\display\displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\display\core.py", line 2687, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\downloads\renpy-8.2.1-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "D:\downloads\renpy-8.2.1-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/dialogues/quests.rpy", line 44, in execute
    screen quest_description:
  File "game/dialogues/quests.rpy", line 44, in execute
    screen quest_description:
  File "game/dialogues/quests.rpy", line 49, in execute
    window:
  File "game/dialogues/quests.rpy", line 55, in execute
    text quest_description:
  File "D:\downloads\renpy-8.2.1-sdk\renpy\text\text.py", line 1717, in __init__
    raise Exception("Cannot display {0!r} as text.".format(i))
Exception: Cannot display None as text.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Staszic The Game 1.0
Mon Mar 18 23:36:06 2024
