I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 76, in script
    monika "luj"
ScriptError: could not find label 'up'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\downloads\renpy-8.2.1-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "D:\downloads\renpy-8.2.1-sdk\renpy\main.py", line 635, in main
    run(restart)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\main.py", line 145, in run
    renpy.execution.run_context(True)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/script.rpy", line 76, in script
    monika "luj"
  File "D:\downloads\renpy-8.2.1-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'up'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Staszic The Game 1.0
Sun Mar 17 22:34:04 2024
