I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/dialogues/corridor.rpy", line 130, in script
    if "key" in inventory:
  File "game/dialogues/corridor.rpy", line 130, in <module>
    if "key" in inventory:
NameError: name 'inventory' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/dialogues/corridor.rpy", line 130, in script
    if "key" in inventory:
  File "D:\downloads\renpy-8.2.1-sdk\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "D:\downloads\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\downloads\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/dialogues/corridor.rpy", line 130, in <module>
    if "key" in inventory:
NameError: name 'inventory' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Staszic The Game 1.0
Mon Mar 18 21:50:04 2024
